# Generated by Django 5.0.2 on 2024-02-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
    ]
