# Generated by Django 5.0.2 on 2024-02-15 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fundProject.categories'),
        ),
    ]
