# Generated by Django 5.0.2 on 2024-02-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundProject', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categories',
            constraint=models.UniqueConstraint(fields=('categoryName',), name='unique_category_name'),
        ),
    ]
