# Generated by Django 5.0.1 on 2024-02-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user_id',
        ),
    ]
