# Generated by Django 5.0.2 on 2024-02-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=285)),
                ('details', models.TextField()),
                ('category', models.CharField()),
                ('images', models.CharField()),
                ('tags', models.TextField()),
                ('totalTarget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startTime', models.DateTimeField(auto_now=True)),
                ('endTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
