# Generated by Django 5.0.2 on 2024-02-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundProject', '0002_project'),
        ('fundProject', '0003_comment_commentreports_donation_projectreports_rate_and_more'),
    ]

    operations = [
    ]
